export const activities = [
  {
    title: "20km Run & Walking Tour",
    description: "A long run/walk across Berlin’s main sights — the best way to see the city in one day.",
    location: "https://maps.app.goo.gl/MwXhs9Ck84nDLwGd8",
    photoUrl: "https://source.unsplash.com/800x600/?berlin,run",
    tags: ["DILLAN_SPECIAL", "SEASON_ALL"],
  },
  {
    title: "Climbing at Teufelsberg",
    description: "Climb the Cold War spy station, leave your graffiti mark, then watch the sunset with Berliners.",
    location: "https://maps.app.goo.gl/RHPb8v4YfB7J8xE17",
    photoUrl: "https://source.unsplash.com/800x600/?berlin,teufelsberg",
    tags: ["HISTORIC", "PARTY", "SEASON_SUMMER"],
  },
  {
    title: "Longboards & Picnic at Tempelhof",
    description: "Rent longboards, pack a frisbee, and picnic on the old airport runway. Sunset is magical.",
    location: "https://maps.app.goo.gl/tuZxqqwSfohzK2wA7",
    photoUrl: "https://source.unsplash.com/800x600/?tempelhof,berlin",
    tags: ["DILLAN_SPECIAL", "SEASON_SUMMER"],
  },
  {
    title: "Climbing WWII Bunker",
    description: "Scale a World War II bunker turned climbing wall. Unique Berlin fitness & history mash-up.",
    location: "https://maps.app.goo.gl/5hY7Q7fPtwN9Aq1y5",
    photoUrl: "https://source.unsplash.com/800x600/?berlin,bunker,climbing",
    tags: ["HISTORIC", "SEASON_ALL"],
  },
  {
    title: "Beer & Kebab Crawl in Prenzlauer Berg",
    description: "Beers at Prater Biergarten, a legendary döner kebab, then wander tipsy through the neighborhood.",
    location: "https://maps.app.goo.gl/TZ9ktj67qR2RwVrA7",
    photoUrl: "https://source.unsplash.com/800x600/?biergarten,berlin",
    tags: ["FOOD", "PARTY", "SEASON_SUMMER"],
  },
  {
    title: "Neukölln Market Abendbrot",
    description: "Shop for spreads, bread, and veggies at a local market, then enjoy a German Abendbrot dinner.",
    location: "https://maps.app.goo.gl/zXK6i5WcM6s8aZkQ9",
    photoUrl: "https://source.unsplash.com/800x600/?market,berlin",
    tags: ["FOOD", "SEASON_ALL"],
  },
  {
    title: "Christmas Market Glühwein",
    description: "Get festive with glühwein, candied nuts, and Feuerzangenbowle at Berlin’s Christmas markets.",
    location: "https://maps.app.goo.gl/rRzXUknhQv7CkzGp6",
    photoUrl: "https://source.unsplash.com/800x600/?christmas,berlin",
    tags: ["FOOD", "SEASON_WINTER"],
  },
  {
    title: "Show Off Dillan’s Friends",
    description: "Meet some of Dillan’s favorite people in Berlin — a truly local experience.",
    location: "https://maps.app.goo.gl/yT2BdGjzThhY3FpU6",
    photoUrl: "https://source.unsplash.com/800x600/?friends,berlin",
    tags: ["DILLAN_SPECIAL", "SEASON_ALL"],
  },
  {
    title: "Berlin Club Marathon",
    description: "See how long you can last in Berlin’s famous 40-hour parties. Legendary stamina challenge.",
    location: "https://maps.app.goo.gl/TUJEnMWW8ZxFjSVf6",
    photoUrl: "https://source.unsplash.com/800x600/?club,berlin",
    tags: ["PARTY", "SEASON_ALL"],
  },
  {
    title: "Union Berlin Football Match",
    description: "Buy a Union Berlin shirt, join the ultras, and chant with the crowd at a home game.",
    location: "https://maps.app.goo.gl/Ek7xK9Ya9LkpxPWf7",
    photoUrl: "https://source.unsplash.com/800x600/?football,berlin",
    tags: ["PARTY", "SEASON_ALL"],
  },
  {
    title: "BBQ Boat on Lake Müggelsee",
    description: "Hire a BBQ boat on Berlin’s largest lake. Germans plan ahead — book early!",
    location: "https://maps.app.goo.gl/kSnzkbZn3EJQQf5R7",
    photoUrl: "https://source.unsplash.com/800x600/?lake,berlin",
    tags: ["DILLAN_SPECIAL", "SEASON_SUMMER"],
  },
  {
    title: "Vabali Sauna Day",
    description: "Relax Berlin-style: textile-free sauna rituals at Vabali spa, or local Aufguss on Monday nights.",
    location: "https://maps.app.goo.gl/q8WTtUG6bNRoWME38",
    photoUrl: "https://source.unsplash.com/800x600/?sauna,berlin",
    tags: ["DILLAN_SPECIAL", "SEASON_ALL"],
  },
  {
    title: "Reichstag Glass Dome",
    description: "Visit the German parliament’s glass dome for panoramic views. Book tickets in advance.",
    location: "https://maps.app.goo.gl/CvCKoXthfak9M7YH6",
    photoUrl: "https://source.unsplash.com/800x600/?reichstag,berlin",
    tags: ["HISTORIC", "SEASON_ALL"],
  },
  {
    title: "Museum Island",
    description: "Explore Berlin’s famous museums: Neues Museum, Pergamon, and more on Museuminsel.",
    location: "https://maps.app.goo.gl/HKXxHcM6vPVX3e1U8",
    photoUrl: "https://source.unsplash.com/800x600/?museum,berlin",
    tags: ["HISTORIC", "SEASON_ALL"],
  },
  {
    title: "Holocaust Memorial",
    description: "Walk through the haunting field of concrete slabs, a powerful reminder of history.",
    location: "https://maps.app.goo.gl/FkYZfjUo28P84xAQA",
    photoUrl: "https://source.unsplash.com/800x600/?holocaust,berlin",
    tags: ["HISTORIC", "SEASON_ALL"],
  },
  {
    title: "East Side Gallery",
    description: "See the longest remaining section of the Berlin Wall, covered in colorful murals.",
    location: "https://maps.app.goo.gl/W4Eni1hmuRzhrVXh8",
    photoUrl: "https://source.unsplash.com/800x600/?berlinwall,berlin",
    tags: ["HISTORIC", "SEASON_ALL"],
  },
  {
    title: "Mauerpark Karaoke",
    description: "Join the Sunday flea market and open-air karaoke at Mauerpark. Berlin at its quirkiest.",
    location: "https://maps.app.goo.gl/z1mP4sq6WwFvN6PQ8",
    photoUrl: "https://source.unsplash.com/800x600/?mauerpark,berlin",
    tags: ["PARTY", "SEASON_SUMMER"],
  },
  {
    title: "Treptower Park & Soviet Memorial",
    description: "Vast green park with striking Soviet war memorials. A glimpse into Berlin’s past.",
    location: "https://maps.app.goo.gl/tzEJkM5FkRPrM3bA7",
    photoUrl: "https://source.unsplash.com/800x600/?treptower,berlin",
    tags: ["HISTORIC", "SEASON_ALL"],
  },
  {
    title: "Unterwelten Bunker Tour",
    description: "Go underground with Berliner Unterwelten — explore tunnels, bunkers, and Cold War history.",
    location: "https://maps.app.goo.gl/D7cPCjW6jvDWWfwH6",
    photoUrl: "https://source.unsplash.com/800x600/?bunker,underground,berlin",
    tags: ["HISTORIC", "SEASON_ALL"],
  },
  {
    title: "Holzmarkt Riverside",
    description: "Creative riverside spot with bars, food stalls, and art. Relaxed Berlin vibes by the Spree.",
    location: "https://maps.app.goo.gl/H5Sy9aYZZZQutXe9A",
    photoUrl: "https://source.unsplash.com/800x600/?spree,berlin",
    tags: ["PARTY", "SEASON_SUMMER"],
  },
  {
    title: "Boxhagener Platz Flea Market",
    description: "Hip flea market and neighborhood vibe in Friedrichshain. Sundays are best.",
    location: "https://maps.app.goo.gl/s48K6jH98N27FcJ38",
    photoUrl: "https://source.unsplash.com/800x600/?flea,market,berlin",
    tags: ["FOOD", "PARTY", "SEASON_SUMMER"],
  },
  {
    title: "Sonnenallee Turkish Quarter",
    description: "Explore Berlin’s ‘Little Turkey’: kebabs, baklava, and cultural mix in Neukölln.",
    location: "https://maps.app.goo.gl/PV2Rm4xLfYcPqKep8",
    photoUrl: "https://source.unsplash.com/800x600/?turkish,food,berlin",
    tags: ["FOOD", "SEASON_ALL"],
  },
  {
    title: "Prenzlauer Berg Walk",
    description: "Start at the Wasserturm and wander through leafy streets, cafes, and pretty facades.",
    location: "https://maps.app.goo.gl/DKcxAfyMzTkP3XpK7",
    photoUrl: "https://source.unsplash.com/800x600/?prenzlauerberg,berlin",
    tags: ["DILLAN_SPECIAL", "SEASON_ALL"],
  },
  {
    title: "Tiergarten Stroll",
    description: "Berlin’s central park. Perfect for a relaxed walk, picnic, or cycle ride.",
    location: "https://maps.app.goo.gl/8fhHZ8t3nnbDA5XD6",
    photoUrl: "https://source.unsplash.com/800x600/?tiergarten,berlin",
    tags: ["SEASON_ALL"],
  },
];
